name: Database Migrations


on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Appwrite
        uses: appwrite/setup-for-appwrite@70fbed40c61073e0c626d5e843312520190d4667
        with:
          method: email
          email: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          force: true
          all: true
          actions: |-
            push collections
  